### ISSUE TITLE
Differences between this plugin and the Taxonomy_MetaData helper class

### ISSUE THREAD

**Issue by austinjreilly** [jcchavezs/cmb2-taxonomy#2]
Is there a compelling reason why I would use this plugin instead of the [Taxonomy_MetaData helper class](https://github.com/jtsternberg/Taxonomy_MetaData)? In WebDevStudios/CMB2@09d6c56304547d4f8969897aef85de66d8f51475, @jtsternberg writes that this is 

```
Similar to Taxonomy_MetaData, but uses a custom table for taxonomy term meta storage.
```

Why would I care about using a custom table or not?

**Comment by jcchavezs** [comment]
Hi @austinjreilly,

There is a [discussion](https://github.com/jtsternberg/Taxonomy_MetaData/issues/23#issuecomment-85684863) you can have a look at. My point is that using a custom table is better both in scalability and "architecture" (if the term works for WordPress).

**Comment by jtsternberg** [comment]
This is actually a good discussion on the matter: http://wordpress.stackexchange.com/questions/47915/should-i-use-custom-post-types-or-a-custom-database-tables-for-plugin-developmen

First sentence:

> You should be skeptical of anyone who says that there is a single "right" way. The right way depends on the situation.

There are pros/cons to both, and different projects will benefit from different solutions.
