### ISSUE TITLE
1.0.2 Breaks WP 4.4

### ISSUE THREAD

**Issue by joshuadavidnelson** [jcchavezs/cmb2-taxonomy#8]
Just updated a (staging) site to WP 4.4. It looks like your `function_exists` statements are not in the current plugin repo version. This is a fatal error, so you might want to update that asap, as today is the new WP version release.

**Comment by ingageco** [comment]
Same issue here - just wrapped them in function_exists to recover.

**Comment by israelshmueli** [comment]
Please... Make the fix available also on WordPress.org. People are experiencing "white screen of death"  after upgrading to WP 4.4

**Comment by joshuadavidnelson** [comment]
@jcchavezs fixed this issue.
